name: appreneur
favicon: null
layout_spectrum: 0.36532855592668056
typography_spectrum: 0.6699965028092265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6995755310636014
  lightness: 0.42397766723297536
  saturation: 0.31579887331463397
  rhythmicContrast: 0.656677016755566
purpose: []
